name: ThunderHeart
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5018797
  brandStrength: 1
  lightness: 0.8546366
  brandColors:
    - '#770101'
    - '#00002F'
    - '#FC4B01'
    - '#026D80'
    - '#AC4341'
  rhythmicContrast: 0.835213
typography_spectrum: 0.7922078461851925
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.05513784
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
