name: ThunderHeart Guidance
favicon: null
layout_spectrum: 0.86092
typography_spectrum: 0.65994
title: ThunderHeart Guidance
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bfbfbf'
    - '#010001'
    - '#7c7c7c'
    - '#585858'
    - '#9e9e9e'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
