name: ThunderHeart Guidance
favicon: null
layout_spectrum: 0.26696
typography_spectrum: 0.57657
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ThunderHeart Guidance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#770101'
    - '#00002F'
    - '#FC4B01'
    - '#026D80'
    - '#AC4341'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
