typography_spectrum: 0.5082586475528112
color:
  brandColors:
    - '#FA1800'
    - '#FF7802'
    - '#2D001C'
    - '#BE4C33'
    - '#FECC5A'
  brandStrength: 0.34929179895752216
  lightness: 0.5437516096427041
  saturation: 0.8360003961063
  rhythmicContrast: 0.001651166659309575
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7683794972241516
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Simon Esler
  email: esler.simon@gmail.com
name: ThunderHeart Guidance
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Custom Ceremonies
    id: 6851ef60-ef7d-4854-8fec-4b47c24635ed
    type: content
  - name: Private Mindfulness & Meditation
    id: c25f00c8-ab0d-453b-8485-49bfdd16ce32
    type: content
  - name: Workplace Wellness
    id: 804a3f7d-3f27-4fb5-b32f-90df503bc9a5
    type: content
  - name: Kids Yoga
    id: cc2129e7-ee4f-49e7-a8a9-577902837d5c
    type: content
  - name: About
    id: 554e916b-13b5-4f8b-a93d-65ac09a39e7c
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/68f936ef-ccae-4505-a219-440d5295caa1.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ThunderHeart Guidance
content: []
description: >-
  :: Simon Esler
  ::                                                                 
  Mindfulness Coach - Life-Cycle Celebrant - Metaphysical Minister - Kids Yoga
  Teacher
purpose:
  - type: contact
    url: 'tel:4164576581'
    label: call // text 4164576581
  - type: contact
    url: 'mailto:esler.simon@gmail.com'
    label: email
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1f0db21c-b046-4a58-bd0f-4b9b056b2318.png
