name: ThunderHeart
favicon: null
layout_spectrum: 0.32412
typography_spectrum: 0.30372
title: ThunderHeart Guidance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#829ab6'
    - '#685f5a'
    - '#363030'
  brandStrength: 0.709092945093289
  lightness: 0.132045577513054
  saturation: 0.7735590992961079
  rhythmicContrast: 0.040256319334730506
purpose: []
