name: ThunderHeart
favicon: null
layout_spectrum: 0.8663223460316658
typography_spectrum: 0.7922078461851925
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.709092945093289
  lightness: 0.132045577513054
  saturation: 0.7735590992961079
  rhythmicContrast: 0.040256319334730506
purpose: []
